export * from "./shared";
export * from "./or_v1p2_scopes";
export * from "./or_v1p2_rostering_service_schema";
export * from "./or_v1p2_gradebook_service_schema";
export * from "./or_v1p2_resource_service_schema";
export * from "./or_v1p2_rostering_restbinding_schema";
export * from "./or_v1p2_gradebook_restbinding_schema";
export * from "./or_v1p2_resource_restbinding_schema";
export * from "./or_v1p2_csv_binding_schema";

import {
  AcademicSessionsCsvDocumentSchema,
  CategoriesCsvDocumentSchema,
  ClassResourcesCsvDocumentSchema,
  ClassesCsvDocumentSchema,
  CourseResourcesCsvDocumentSchema,
  CoursesCsvDocumentSchema,
  DemographicsCsvDocumentSchema,
  EnrollmentsCsvDocumentSchema,
  LineItemLearningObjectiveIdsCsvDocumentSchema,
  LineItemsCsvDocumentSchema,
  LineItemScoreScalesCsvDocumentSchema,
  ManifestCsvDocumentSchema,
  OneRosterCsvBindingPackageSchema,
  OrgsCsvDocumentSchema,
  ResourcesCsvDocumentSchema,
  ResultLearningObjectiveIdsCsvDocumentSchema,
  ResultsCsvDocumentSchema,
  ResultScoreScalesCsvDocumentSchema,
  RolesCsvDocumentSchema,
  ScoreScalesCsvDocumentSchema,
  UserProfilesCsvDocumentSchema,
  UserResourcesCsvDocumentSchema,
  UsersCsvDocumentSchema,
} from "./or_v1p2_csv_binding_schema";
import { GradebookRestBindingOperationSchemas } from "./or_v1p2_gradebook_restbinding_schema";
import {
  AssessmentLineItemSchema,
  AssessmentLineItemSetSchema,
  AssessmentResultSchema,
  AssessmentResultSetSchema,
  CategorySchema,
  CategorySetSchema,
  GuidPairSetSchema,
  LineItemSchema,
  LineItemSetSchema,
  ResultSchema,
  ResultSetSchema,
  ScoreScaleSchema,
  ScoreScaleSetSchema,
  SingleAssessmentLineItemSchema,
  SingleAssessmentResultSchema,
  SingleCategorySchema,
  SingleLineItemSchema,
  SingleResultSchema,
  SingleScoreScaleSchema,
} from "./or_v1p2_gradebook_service_schema";
import { ResourceRestBindingOperationSchemas } from "./or_v1p2_resource_restbinding_schema";
import { ResourceSchema, ResourceSetSchema, SingleResourceSchema } from "./or_v1p2_resource_service_schema";
import { RosteringRestBindingOperationSchemas } from "./or_v1p2_rostering_restbinding_schema";
import {
  AcademicSessionSchema,
  AcademicSessionSetSchema,
  ClassSchema,
  ClassSetSchema,
  CourseSchema,
  CourseSetSchema,
  DemographicsSchema,
  DemographicsSetSchema,
  EnrollmentSchema,
  EnrollmentSetSchema,
  OrgSchema,
  OrgSetSchema,
  SingleAcademicSessionSchema,
  SingleClassSchema,
  SingleCourseSchema,
  SingleDemographicsSchema,
  SingleEnrollmentSchema,
  SingleOrgSchema,
  SingleUserSchema,
  UserSchema,
  UserSetSchema,
} from "./or_v1p2_rostering_service_schema";
import { ImsxStatusInfoSchema } from "./shared";

export const OneRoster12DerivedZodTemplates = {
  academicSession: AcademicSessionSchema,
  academicSessionSet: AcademicSessionSetSchema,
  class: ClassSchema,
  classSet: ClassSetSchema,
  course: CourseSchema,
  courseSet: CourseSetSchema,
  demographics: DemographicsSchema,
  demographicsSet: DemographicsSetSchema,
  enrollment: EnrollmentSchema,
  enrollmentSet: EnrollmentSetSchema,
  org: OrgSchema,
  orgSet: OrgSetSchema,
  user: UserSchema,
  userSet: UserSetSchema,
  singleAcademicSession: SingleAcademicSessionSchema,
  singleClass: SingleClassSchema,
  singleCourse: SingleCourseSchema,
  singleDemographics: SingleDemographicsSchema,
  singleEnrollment: SingleEnrollmentSchema,
  singleOrg: SingleOrgSchema,
  singleUser: SingleUserSchema,
  lineItem: LineItemSchema,
  lineItemSet: LineItemSetSchema,
  result: ResultSchema,
  resultSet: ResultSetSchema,
  category: CategorySchema,
  categorySet: CategorySetSchema,
  scoreScale: ScoreScaleSchema,
  scoreScaleSet: ScoreScaleSetSchema,
  assessmentLineItem: AssessmentLineItemSchema,
  assessmentLineItemSet: AssessmentLineItemSetSchema,
  assessmentResult: AssessmentResultSchema,
  assessmentResultSet: AssessmentResultSetSchema,
  guidPairSet: GuidPairSetSchema,
  singleLineItem: SingleLineItemSchema,
  singleResult: SingleResultSchema,
  singleCategory: SingleCategorySchema,
  singleScoreScale: SingleScoreScaleSchema,
  singleAssessmentLineItem: SingleAssessmentLineItemSchema,
  singleAssessmentResult: SingleAssessmentResultSchema,
  resource: ResourceSchema,
  resourceSet: ResourceSetSchema,
  singleResource: SingleResourceSchema,
  rosteringRestBindingOperations: RosteringRestBindingOperationSchemas,
  gradebookRestBindingOperations: GradebookRestBindingOperationSchemas,
  resourceRestBindingOperations: ResourceRestBindingOperationSchemas,
  manifestCsvDocument: ManifestCsvDocumentSchema,
  academicSessionsCsvDocument: AcademicSessionsCsvDocumentSchema,
  categoriesCsvDocument: CategoriesCsvDocumentSchema,
  classesCsvDocument: ClassesCsvDocumentSchema,
  classResourcesCsvDocument: ClassResourcesCsvDocumentSchema,
  courseResourcesCsvDocument: CourseResourcesCsvDocumentSchema,
  coursesCsvDocument: CoursesCsvDocumentSchema,
  demographicsCsvDocument: DemographicsCsvDocumentSchema,
  enrollmentsCsvDocument: EnrollmentsCsvDocumentSchema,
  lineItemLearningObjectiveIdsCsvDocument: LineItemLearningObjectiveIdsCsvDocumentSchema,
  lineItemsCsvDocument: LineItemsCsvDocumentSchema,
  lineItemScoreScalesCsvDocument: LineItemScoreScalesCsvDocumentSchema,
  orgsCsvDocument: OrgsCsvDocumentSchema,
  resourcesCsvDocument: ResourcesCsvDocumentSchema,
  resultLearningObjectiveIdsCsvDocument: ResultLearningObjectiveIdsCsvDocumentSchema,
  resultsCsvDocument: ResultsCsvDocumentSchema,
  resultScoreScalesCsvDocument: ResultScoreScalesCsvDocumentSchema,
  rolesCsvDocument: RolesCsvDocumentSchema,
  scoreScalesCsvDocument: ScoreScalesCsvDocumentSchema,
  userProfilesCsvDocument: UserProfilesCsvDocumentSchema,
  userResourcesCsvDocument: UserResourcesCsvDocumentSchema,
  usersCsvDocument: UsersCsvDocumentSchema,
  csvBindingPackage: OneRosterCsvBindingPackageSchema,
  imsxStatusInfo: ImsxStatusInfoSchema,
} as const;
