FROM docker.io/oven/bun:1.4.0

WORKDIR /app

COPY scripts/interop-fixtures/ltijs-real/package.json /app/package.json
RUN bun install

COPY scripts/interop-fixtures/ltijs-real /app

CMD ["bun", "run", "start"]
